### ISSUE TITLE
Colorcodes

### ISSUE THREAD

**Issue by martijnpu** [aBooDyy/Progress-Expansion#3]
Hi,

I noticed I can't use nummeric colorcodes in the çomplete-parameter.
This means the following placeholder is invalid:
`%progress_bar_{players_online}_c:&a|_p:&e|_r:&7|_m:server_max_players_fullbar:&4We're full!%`
And this one is valid:
`%progress_bar_{players_online}_c:&a|_p:&e|_r:&7|_m:server_max_players_fullbar:&cWe're full!%`

If you don't want to fix it it's okay, I only letting you know what I've found. I like your placeholder a lot!

martijnpu

**Comment by aBooDyy** [comment]
Hi again,
Thanks for letting me know, I'm actually not doing anything for the color codes, PlaceholderAPI is handling that. But i'll look into it for sure and fix it.

Glad you liked it!

**Comment by aBooDyy** [comment]
Both placeholders are working fine, just noticed that you didn't add curly braces `{}` to the max parameter for `server_max_players` placeholder.
If you want to use a placeholder inside any Progress placeholder, you'll have to put it in curly braces `{}` without adding the percentage symbols `%%`.

It could be the issue but i'm not so sure, try it please since there's nothing wrong with numeric color codes.

**Comment by aBooDyy** [comment]
Hey there @martijnpu,

So, have you tried what i said? Did it fix the issue?
Let me know how it went for you.

Issue will be closed in few days if i didn't receive a reply from you.
